// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240813192702_fourth")]
    partial class fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            Country = "USA",
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1308),
                            FullAddress = "123 Main St",
                            IsDeleted = false,
                            PostalCode = 10001,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            City = "Los Angeles",
                            Country = "USA",
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1319),
                            FullAddress = "456 Elm St",
                            IsDeleted = false,
                            PostalCode = 90001,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            City = "Chicago",
                            Country = "USA",
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1324),
                            FullAddress = "789 Pine St",
                            IsDeleted = false,
                            PostalCode = 60007,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            City = "Houston",
                            Country = "USA",
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1328),
                            FullAddress = "321 Oak St",
                            IsDeleted = false,
                            PostalCode = 77001,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            City = "Phoenix",
                            Country = "USA",
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1333),
                            FullAddress = "654 Maple St",
                            IsDeleted = false,
                            PostalCode = 85001,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.ExtraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AdditionalPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExtraItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalPrice = 1.0,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1443),
                            IsDeleted = false,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalPrice = 1.5,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1447),
                            IsDeleted = false,
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalPrice = 1.25,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1451),
                            IsDeleted = false,
                            Name = "Mushrooms"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalPrice = 2.0,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1455),
                            IsDeleted = false,
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalPrice = 0.75,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1458),
                            IsDeleted = false,
                            Name = "Onions"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1570),
                            Description = "Juicy beef burger",
                            IsDeleted = false,
                            Name = "Burger",
                            OrderCount = 10,
                            Price = 8.9900000000000002,
                            ViewCount = 50
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1578),
                            Description = "Cheese and pepperoni",
                            IsDeleted = false,
                            Name = "Pizza",
                            OrderCount = 20,
                            Price = 12.99,
                            ViewCount = 100
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1583),
                            Description = "Creamy Alfredo pasta",
                            IsDeleted = false,
                            Name = "Pasta",
                            OrderCount = 15,
                            Price = 10.99,
                            ViewCount = 75
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1587),
                            Description = "Fresh garden salad",
                            IsDeleted = false,
                            Name = "Salad",
                            OrderCount = 8,
                            Price = 7.9900000000000002,
                            ViewCount = 40
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1591),
                            Description = "Spicy chicken tacos",
                            IsDeleted = false,
                            Name = "Tacos",
                            OrderCount = 12,
                            Price = 9.9900000000000002,
                            ViewCount = 60
                        });
                });

            modelBuilder.Entity("DAL.Entities.MenuDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExtraItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExtraItemId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1977),
                            ExtraItemId = 1,
                            IsDeleted = false,
                            MenuId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1985),
                            ExtraItemId = 2,
                            IsDeleted = false,
                            MenuId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1989),
                            ExtraItemId = 3,
                            IsDeleted = false,
                            MenuId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1993),
                            ExtraItemId = 4,
                            IsDeleted = false,
                            MenuId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(1997),
                            ExtraItemId = 5,
                            IsDeleted = false,
                            MenuId = 5
                        });
                });

            modelBuilder.Entity("DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderSize")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DAL.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExtraItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ExtraItemId");

                    b.HasIndex("MenuId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(394),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsAdmin = true,
                            IsDeleted = false,
                            LastName = "User",
                            Password = "admin123",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(398),
                            Email = "john@example.com",
                            FirstName = "John",
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Doe",
                            Password = "password123",
                            Username = "john"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1985, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(405),
                            Email = "jane@example.com",
                            FirstName = "Jane",
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Smith",
                            Password = "password123",
                            Username = "jane"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1975, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(411),
                            Email = "michael@example.com",
                            FirstName = "Michael",
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Brown",
                            Password = "password123",
                            Username = "michael"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1995, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2024, 8, 13, 22, 27, 0, 385, DateTimeKind.Local).AddTicks(417),
                            Email = "emily@example.com",
                            FirstName = "Emily",
                            IsAdmin = false,
                            IsDeleted = false,
                            LastName = "Clark",
                            Password = "password123",
                            Username = "emily"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Address", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.MenuDetail", b =>
                {
                    b.HasOne("DAL.Entities.ExtraItem", "ExtraItem")
                        .WithMany("MenuDetails")
                        .HasForeignKey("ExtraItemId");

                    b.HasOne("DAL.Entities.Menu", "Menu")
                        .WithMany("MenuDetails")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraItem");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("DAL.Entities.Order", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.OrderDetail", b =>
                {
                    b.HasOne("DAL.Entities.Address", "Address")
                        .WithMany("OrderDetails")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.ExtraItem", "ExtraItem")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ExtraItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Entities.Menu", "Menu")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("ExtraItem");

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Entities.Address", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DAL.Entities.ExtraItem", b =>
                {
                    b.Navigation("MenuDetails");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DAL.Entities.Menu", b =>
                {
                    b.Navigation("MenuDetails");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
